addons:
  code_climate:
    repo_token: 2bbc15899ab1b0b47c7157a5901bf6b460168b197ac2e0cf4f66a91da5b700bd
language: ruby
rvm:
- 2.2.2
before_install:
- sudo apt-get install libicu-dev -y
- sudo apt-get install libqt4-dev libqtwebkit-dev -y
before_script:
- cp config/database.psql.yml config/database.yml
- psql -c 'create database hpi_swt2_test;' -U postgres
script:
- RAILS_ENV=test bundle exec rake db:migrate
- xvfb-run bundle exec rspec spec/
notifications:
  email: false
  slack:
    secure: Q6Z+IGJSxPsitPHHT4tzl3du+jIG5KVo4IRTGkhAW+9ekujD7KvqSJ8hl2Cet0LUKae8c+hzuZJN4nY+b6i7hnM0m1XRRZCTTdsmyq6NVKfDzICT37C7BXaytgzirRiqajUC+znoZNOzbl4bjcXYP5Hrap/woTxP74f5/xxbCA/1sQRft/n6Yl0UbzKkWwOjdSQI13jRmwwSx77BaK+8wy55D+FTTKjgctYuAvSKOxbOAdaMgKJqrsO+ShjMDvue4YHLM5dGsmZgLUXIRYMm/3kkx29dCoUOmYQEzDxf9bMOXMCbGeGtzvA/jjNaxDuRgsB5k3w1M/klnY3cpDE1PsBMcvTRiw1P2gCPxGRzkkNbjmo/98Qo7QMHHJ1Qj11gxGNW66iiQF+tw3DfqC61bT04QZJjznr57pzAkU52Lm4G7R//nJadoy5Nv4FNLVjxOOX2kgL3m0oqX7KgcaL6BD3A14IeqKnhSU2flFiG3sn2FeE7CHgHZ+F8CwiZ870IVB/ETE7vwxE2sv9aDzxGzbXmjzVl0+Z3EszkVoOo1G+p3QKIjWhMbMMPjK/E3rURia0nnql2k8Cilk6vWfNZvM8KcfH7N4cH16/nZMoGwFvWmNeRiMC+bxBISMfvz7ZKyaSOUsVD91gCM9vfUqYAj8dQey1r7z+Ne3zH0U75ICs=
    on_success: change
    on_failure: change

deploy:
  provider: heroku
  api_key:
    secure: DuNFMV4RSf+a5ddK2cgZkXkVb+J5EpV3bbZRyi2vKpPNWm6tdaU1lN1eWBUGv0DiLz9uIOEx5c30dn3jGY7IBlj8WInKqXWp7XvwoVYUV5KM6hezT9mgrO7iFjLJpIZN8l/y2q7BzepN895UDvIZFbJwUMl5Qqc8BWUAy0IrAVtMNfav53QBKga7xzh9k09rH3W3BpEC/fqfY8JmLY7hqOwYdZd9Xq36auyb0Vsq4IYIGUhqZ8QjzrZZ11gdsR9HSzStbi8DlLiJy3VfpRJdVRhV3J/KzWibL2lqqBt3uqcPAk7bJvWO3DC5OitFUoYID4an12Y5Wl6VpLxll0Eu2Y5918gO/vdapLJiWcHSsELyI8z1NExazlrXvuEq9ibSCfEq86Qy1wydGWvMQyW61i4XPeTqHlNaylxwpdn3gtrwytGYnEHOxnoCd3G4tW+sGDiQ9miTjoGzg8jbwmvxASlUrCe4wIZESf2KW0UKYQ/QpNgiAsfkmI7LW3I2Zo8WVmgLGZM/0xRWopPvkp5ecCU9lDi6Npw4HjHBKJObuxQSnnwW+DNI0bTL49li9dU8T1nSw7huHZ0loyzW/XYElumTpHpYk1g6RfklhKeG8Yn9vV0yA530J97dEsXzq34fNjE6GNda2380n9G0EILACkvbeBTdxnyKiW98SixcN8A=
  app:
    master: wimi-portal
    dev: wimi-portal-dev
  on:
    repo: hpi-swt2/wimi-portal
  run:
  - rake db:migrate
  - rake db:seed
  - restart
