addons:
  code_climate:
    repo_token: 2bbc15899ab1b0b47c7157a5901bf6b460168b197ac2e0cf4f66a91da5b700bd
language: ruby
rvm:
- 2.2.2
sudo: false
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database hpi_swt2_test;' -U postgres
script:
- bundle exec rake db:test:prepare
- xvfb-run bundle exec rspec spec/
notifications:
  email: false
  slack:
    rooms:
      - secure: R5DdA6W4CQMRcEyfJ9aqZAVnxmV6Yo6WMHM8lqgJcYhWZofI3ZWlKEmnyFgLgvSSOKVHIjQkmS3PHFaEhKz90dVwfI5y9nj/ZnAwoGjC/OIXPskt/XnTBQAjK5HZSdbOstdCkotIfkMnfNFhSlWLZoLCYDtf3tj/Fau1SQan/KXdmqEWt2mWzfZ1NqOIH0A07oEgtNAkMQJs4DyTBIx06pjbuLEGia6e5cyOfW0HDbAIgqPamhM2a6VmFBGXv0bAHm8penV/cenKKFUk7a4qBUc8aagP51aBSeQdNeQ7uVLTs+IOswXydfzzGQQFRGf/9BFYdX09QJYGc89ChJgYIqPNCr6tKPVkpjzZaOm159gbNL7B2Rwpq0RlOuuZ6ZerVOtraW89Y2Sba3w1Dka/2bcVUAkCtxqYW1tJ1W7km363IhZOUhDFpU+EDAbKWYwaCWauoRPAjNQVhp8AMeKvXHTiWjeiiOpILCDsSqrmGr5/o1fG8Dbj+si33xtg6+CwOZ/HTAWq4jIv+e+8lCA+h5w9K49V1CCl0gxGtU6DCMN6NcH5z72EC7kZfd8X1yq91mX1SIw9liloAeTnrvchX34ckVWB2lJsuDUD2z3BSj3I8qrVAhpmqmkHlp/0eGS0MuJyIbe2RXAfaA47V3qR6ut8JcXHtX6f69V2cvxTu98=
      - secure: K11ATxX62urMsLl3X5HAdqhgR6EdzPAESyvV0sFIuOJDF1tgwXmmHfmE0I1jaZgtQJjigPkL1hZErB9FWmPrbLG0TSA51c8Bni4DcKvuvvK8bVe62oUEALHjm8XQkwNLP/Xt4MR6hm1yBg8fr/ahlFsY9/q987FpRQCf4RhDowiVfqvQHmH/N/dX96i2FgWV0tRnR2XZGpHoluKM6dD5ruI6mrEH7UA9hU/oZWKcuB7mSsvsxp5XcbYMaN7xM9jlJ0I0w5Ado1L6gS1+k8cnlOSDLOAstLRylQLOsmrz7JQWQ0L52+PcCD8G3J7tbHgd7VKLKrrCaU9TVKKdzEbvmvJSqR239SqRRWL5V1zuuNcYtf1vxZunhifvShs4IgekIP9orX+uFVMIJ43H0x/YxVRfJJrwXedd/70mhIr+qasPtd7yR9RfO8ldAzhKbdbLff606QP20xvAIuTvKj72KiMdheQcwbEZgOGljECVlkaWY9F5E/mJ+gDg9mscvHeQmtxCfUVfhCRSoxosnJy9w2PSqXgqJW4I6iDoFaygMOS/SyJ9CPjes0+BkkUb9weNS+YyTuPQGILTCJVaVThhVK67EN5bsMeUzM8RRJbxYtKs4OlKRwtL6PqnvMdhLahFYsATFyI0ABzV0Vv9Im5O6zu8HSCGYaFjfonDE/x0Eqw=
    on_success: change
    on_failure: change
deploy:
  provider: heroku
  api_key:
    secure: DuNFMV4RSf+a5ddK2cgZkXkVb+J5EpV3bbZRyi2vKpPNWm6tdaU1lN1eWBUGv0DiLz9uIOEx5c30dn3jGY7IBlj8WInKqXWp7XvwoVYUV5KM6hezT9mgrO7iFjLJpIZN8l/y2q7BzepN895UDvIZFbJwUMl5Qqc8BWUAy0IrAVtMNfav53QBKga7xzh9k09rH3W3BpEC/fqfY8JmLY7hqOwYdZd9Xq36auyb0Vsq4IYIGUhqZ8QjzrZZ11gdsR9HSzStbi8DlLiJy3VfpRJdVRhV3J/KzWibL2lqqBt3uqcPAk7bJvWO3DC5OitFUoYID4an12Y5Wl6VpLxll0Eu2Y5918gO/vdapLJiWcHSsELyI8z1NExazlrXvuEq9ibSCfEq86Qy1wydGWvMQyW61i4XPeTqHlNaylxwpdn3gtrwytGYnEHOxnoCd3G4tW+sGDiQ9miTjoGzg8jbwmvxASlUrCe4wIZESf2KW0UKYQ/QpNgiAsfkmI7LW3I2Zo8WVmgLGZM/0xRWopPvkp5ecCU9lDi6Npw4HjHBKJObuxQSnnwW+DNI0bTL49li9dU8T1nSw7huHZ0loyzW/XYElumTpHpYk1g6RfklhKeG8Yn9vV0yA530J97dEsXzq34fNjE6GNda2380n9G0EILACkvbeBTdxnyKiW98SixcN8A=
  app:
    master: wimi-portal
    dev: wimi-portal-dev
  on:
    repo: hpi-swt2/wimi-portal
  run:
  - rake db:migrate
  - rake db:seed
  - restart
